           <div data-role="footer" data-position="fixed">
               <div id="menu-bas" data-role="navbar">
                   <ul>
                       <li>
                           <a href="index.php" rel="external">
                               <img src="../pictures/icons/home.png" style="height: 50px;" />
                           </a>
                       </li>
                       <li>
                           <a href="programmeValrando.php" rel="external">
                               <img src="../pictures/icons/randonnee.png" style="height: 50px;" />
                           </a>
                       </li>
                       <li>
                           <a href="listePropositions.php" rel="external">
                               <img src="../pictures/icons/tour.gif" style="height: 50px;" />
                           </a>
                       </li>
                       <li>
                           <a href="contact.php" rel="external">
                               <img src="../pictures/icons/mail.png" style="height: 50px;" />
                           </a>
                       </li>
                   </ul>
               </div>
           </div><!-- /footer -->
       </div><!-- /page -->
    </body>
</html>