<?php

   /****************************************************************************
    * Auteur:   Pascal Favre
    * Classe:   606_F
    * But:      Pied de page et fermeture du Body et du HTML pour les pages de 
    *           la console d'administration
    ***************************************************************************/

?>
                    <div id="footer">
                <!-- Pied de page de la console d'administration -->
                <div class="footer-text">
                    <b>Copyright Cas Montana 2013</b>
                </div>
            </div>        
        </div>

    </body>
</html>